[package]
name = "nini-ext"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nini-core = { path = "../nini-core" }
libloading = "0.8"

[dev-dependencies]
tempfile = { workspace = true }

[lints.rust]
unsafe_code = "allow"
